### ISSUE TITLE
返回的是实例的 init()，使用的时候很不方便，比如无法 reset

### ISSUE THREAD

**Issue by qingtian5266** [Soya-xy/captcha#1]
应该返回的就是类，并且暴露多个方法，现在使用起来会有很多问题，比如无法重置等。还有例子中的 width pin拼错了

![image](https://user-images.githubusercontent.com/28749518/198972230-c905d7cf-1a09-4ce2-8f66-2cacab75d815.png)

**Comment by Soya-xy** [comment]
参考readme的使用方法即可。 或者提供一下最小复现

**Comment by Soya-xy** [comment]
reset 默认情况应该不需要手动调用吧。。 右上角刷新是可以使用reset 的
